name: Earthquake Alert Bot

# Controls when the workflow will run
on:
  # Runs on a schedule (e.g., every 15 minutes)
  schedule:
    - cron: '*/15 * * * *' # Runs at 0, 15, 30, 45 minutes past the hour

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check_quakes"
  check_quakes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4 # Use the latest checkout action

      # Sets up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Specify your desired Python version

      # Installs dependencies using pip and requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Runs your Python script
      - name: Run earthquake check script
        env:
          # Make GitHub secrets available as environment variables to the script
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py # The command to run your script